# https://hitleap.com/by/HeroCC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitleap
  namespace: default
  labels:
    app: hitleap
  annotations:
    fluxcd.io/automated: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hitleap
  template:
    metadata:
      labels:
        app: hitleap
    spec:
      containers:
      - name: hitleap
        image: pakonda/hitleap@sha256:1835230dd358968874090506414382a397b171e21e6a4f07d9b916fa8d370c79
        envFrom:
          - secretRef:
              name: hitleap-creds

