---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.9.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "10.0.1.254"
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      # https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: true
    globalArguments:
      - "--global.sendanonymoususage"
      #- "--api.insecure=true"
      # Ignore invalid endpoint (our side) certificates
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      # Local IPs and CloudFlare
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
    ports:
      traefik:
        port: 9000
        expose: false
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      #metrics:
      #  port: 8082
      #  expose: true
      #  exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    metrics:
      prometheus:
        entryPoint: metrics
    resources:
      requests:
        memory: 50Mi
        cpu: 300m
      limits:
        memory: 200Mi
