---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "10.0.2.0/24"
