---
git:
  url: "git@github.com:HeroCC/infra"
  branch: master
  path: deployments
  pollInterval: "1m"
additionalArgs:
  - --connect=ws://fluxcloud
# If enabled, fluxd will delete resources that it created, but are no longer present in git
syncGarbageCollection:
  enabled: true
# Enables running Kustomize
manifestGeneration: true
