apiVersion: v1
kind: Secret
metadata:
    name: asf-account-creds
    namespace: default
type: Opaque
data:
    HC1.maFile: ENC[AES256_GCM,data:f3ONkQpMuHjbUlbyra2foXZWk9wBjcJ2epWxsFga2esNVfiOfIAwFuCTwyx5vB344Gv8XC4xAgQmL4yWysCFXpEuDCE+NyKqEl2ircg94toTsJhguiDH0upKpoLFigfzO4SsdlMXkxAtnlP6Zni478CPCfYAqZSXsRlQPM8HTtRh42VvRhxDRwyIdUcGhwlk0k9iQeAo2R8rxwuFgfjOGJeS7Y7lgHjaOGwTJ1i2gTiCevQyHf56MLb7VOEO9KklHo+JXiEhVDoR45qdBse8U2dikK8=,iv:CVuZLJvCFs6B4g21JULsC2NMD2O0jx3QZhGOdJzY0LM=,tag:+NIipih8rZxxG1sSBsqYRA==,type:str]
    HC2.maFile: ENC[AES256_GCM,data:efyrHXomM0NVsV6eYmwxG705GPMbm0bqSs1BnMn6wbMTsuDoGSb/PIxTuAK+XG4pjhzeb8ACazARRGq8p+UlqDjL7VYpMVllL0y3pLLc4+oyqxj42xKqapQQD4QldRi+AEpdaRd4fBv9krwEGyydqJXURRAqhyw64gOsj+KCK+bLKHDgmH0zlNqgsOf0qGZBqzw4D/Iaqa0rHdqUzxSZ9YJ148OJBV3Nu8nXOibFa0rSBLj4zuA5boUiL2edDWwc9UyHqOh79dncXfBXtxj345Tb4VU=,iv:Xbuz0/HsZkxyp0e1sTe7Mq6K3wZCBepMGU1PxVa0qoA=,tag:yKglrh4vwM6Ji4gx9WZBnQ==,type:str]
    HC3.db: ENC[AES256_GCM,data:Df/iPce4e8MUSRQQsxSz8sSFgb1/cgdv34kwtI81oQWeG0Shuf5tgUKNGfn2PnZCKG26TOKQq9vO7EayCw4IqS1cG8i/f5h2cCDKQh2g7m3o8e558eM2qQ==,iv:HhyvzV1duvQvyWiwLON3/0LiRFl6zr2BiQQjT1eBh+I=,tag:PLb207SiAYL9pq4sUVnV1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-09T20:02:06Z'
    mac: ENC[AES256_GCM,data:JJezROePlYAyhkkbLCmlccYnHQx39AmLRQivtYIOV26/rM584dvugy/MfZrFgZUlwVKH7QXLesNP0+nEfjwi1qdM/Xwrju9/MqXYFcJBpB0IHkfEqCwyohJuGQK6tD8vkPTSk999u0q8+OkPMRpEjiFn07PsoCOQ7fcN32TK0ZY=,iv:7OQlXy3YNFjz5prjFR8iw4r6Qeas8akxkIjj3KxrZsU=,tag:FwtGBPtQAWIISntuj5wRIw==,type:str]
    pgp:
    -   created_at: '2020-09-09T19:48:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7R8OyOD8bjEAQ/+LxJgh8wSocmtdZWRhlrqheW12pjnT+XkGXy8oPlNKOOD
            wH0ycq29OS2F9WMfE/mAVrWcL270IqB31rFc+WK5pc62+ZR9DWiZPhPYUMtcUOMi
            mE/1KqNL9SxRDaxFYwKY1Q1eT88KfWwsJwtH2sbgoMG9L3tBecjRaWHX0X90muWW
            hHfHSLuKqwliYu1KyDdodYyIJESyWqVfBSAy7gQItLebbUPQ7/FpUS9C8C/eaKhv
            EyjqILJV8D300RKc5VEtEi95FGGGWPMAMmYceZ9IyGvUJfsjIxcetGeVIPj6aoBw
            yY6VjWM74J+K82XrbDSx7CV+07n9VGvhRmKvnbRNrla5y22wmx9DGlGx20eeL8vu
            SKFqN62/DMfW0AtvBtmlz665YhowCIU7ldC5TJmrJmtp2Rziv3bEdONNIPYH4ouo
            +t4fbP6HOmImFpjXbikI4rsW+c9joncgVSBCbZt37y2BhyX/47OwfSJQWmHjq5WR
            0h5IFf4XZKoxIYu2AauxAbNIGeOOnANf6t4MW8jbkRVQtU4a5b2ZfqtWC7aZLYMw
            qhb17nOZBap/HI0qF8Or4lsBSUXW3ieaf6aHj9xmvq2jj0j3NoJyHJL9bylX8Uod
            LioDGb53iz3Ka0gYO9ppToTJfWoKM3YZTdQX4wc8jR1EhSxMrGfBJfRKgDLNmXfS
            XgFKB4n/DxUyR544DoWbFdQJX+4wSj7KGRs+A3djgyQZ5puIeTSELbfCgIAB/THG
            BRoRXpq75sP4pBXYA6OWRGBotZphO0x5yI3CyP1pT6Um8qQmDOjk5aotvaaf5Xc=
            =0icp
            -----END PGP MESSAGE-----
        fp: C8A1E2D47C35AB1C30288640940ED79CFA122C1A
    -   created_at: '2020-09-09T19:48:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hIwD5/DIMlnnmvcBA/sECVdsAT5Vh/yMwwJdFWJGsHIlB+v9e4STDjnl3cFyXRu+
            feXDFFraNsrLH83MDseA8EB9O73uLWZnNVpEQGZTzCBbLjAwUwlr3sTME5T0axjv
            TE+b16+T1xpQ5Ixa6mXLDxYtrgfmhZEJV05CpIHbaXNdYPUeeH0g5s8f24L7tNJe
            Ae08eOqhV1lbvM7eQsxA0rvQGxzHfO1zxsvJ8jTJtNDZO6wjmBTzCmW1XGztFAPQ
            fycANzExKfEbxga9JYBFlvKeDZpvJnkY4DSptuLhDXG6l4iXkluBIFHmbiOsZA==
            =o/4n
            -----END PGP MESSAGE-----
        fp: FEAE1C9C842D48A03C02C8BF23D2AAAD58DECDA0
    encrypted_regex: ^(data|stringData)$
    version: 3.6.0
