# ArchiSteamFarm 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asf
  namespace: default
  labels:
    app: asf
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.asf: glob:~4.3.*.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asf
  template:
    metadata:
      labels:
        app: asf
    spec:
      containers:
      - name: asf
        image: justarchi/archisteamfarm:master
        ports:
          - containerPort: 1242
        envFrom:
          - secretRef:
              name: asf-cryptkey
        volumeMounts:
          - name: asf-config-volume
            mountPath: /app/config
            readOnly: false
      volumes:
        - name: asf-config-volume
          configMap:
            name: asf-configmap

