apiVersion: v1
kind: Secret
metadata:
    name: mmirror-envsecret
    namespace: default
type: Opaque
data:
    OPENWEATHER_API: ENC[AES256_GCM,data:xVVV1VJ2ZoXtQEmwyLWWVwDtyZvWnFWA8BRfqSi0hhHJCMAabmbuQhryRz8=,iv:xBMSHJrfzxUZXq9TO54LR8QzfWfkk8pnE97pYQIk2gc=,tag:VKfMh+B/EUGk5bF42Z+oPg==,type:str]
    CLASS_SCHEDULE_CAL: ENC[AES256_GCM,data:DriIe4c0Gln1bZivce1mrXaEv/Sk9m7ffl7RWYsVUwLEXX+KmyGDujBf/5LyGIae22NcnU/h8R/1huSWlKDclDqbI2He/WosWyR0erxGrodw6yhwMgnkXpxL+itPSSPBOauqQAomlluzhsRXvyRwMqTrW8DXCkjrdfD5K/rkfvKsDRFr6WckDMisNwtmKS2T25+HGlmkynyftlqGrg1igBLC2beOblIBYSi+3o26YdXA/8T9W3clZipHFV71HMJvAmZV/A==,iv:sbMcrvtrNQPbbvhWEn+W46joMwXoKMJBG4KibOACcH8=,tag:bNBlg0xufbMKsdUx+GoaVQ==,type:str]
    SCHOOL_SCHEDULE_CAL: ENC[AES256_GCM,data:ccaqNUfQDUs0KsKF6CYJQ38X0/AHVoJjxwmQHpmh2XTqpaJjEgl3JtRNif4KDuFhGTav0Hd+5xaGVulpE2RVsbvx/g5+R8LEpkvVDnIzKGIBPO1D/Nd7STM037Wtj6whRvFbEMw1aTk6TYl+j/FjAOx13W9OQhU5JsdTQRZ3l70EvLguTC7+qOfztIbN72MGr4KzCA==,iv:afKflLjPjssSRltOUBAM+qr20FNJ/lrEEcCt0JCjA8E=,tag:SPKoSrHeb4I6YWGRsz0sYg==,type:str]
    PERSONAL_SCHEDULE_CAL: ENC[AES256_GCM,data:uB88wTFlAQGBIUPy0anmN74TFMpn/qTyXasdLD/YA/gsYQyj93Upqsjdx0YHZMnCCYVtEbDUT0JYdc1aakrZCXkjP6Ju1LDAlgjiSaP/N+XKICosMVB9vA1WTfDPvxfUf+8vgYoyCEtBQsqJIwNz0zdipvQ/4oF85vzTA+5FhP1ISVhZMyNyqql64L9pxAw3UQp2bUfuqL4=,iv:OlXTLkLi7kLtsRstmpx7qxDiIGwdQAZCFgftUcUw8c8=,tag:3rMNBggGSSWK+uV46j/GNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-17T02:46:42Z'
    mac: ENC[AES256_GCM,data:ljFlwnLm8XZ/khQbLs2QbC2Aac6joeijiZQ5T8fRDb+CL3J8AX83mf9tMw5Wf5UrY3d4WJt2av+dwWCyJ4vEzOJKckxKh0c0Qe3URJK0b4Fy5vK9kJYJAYhNP7ot3Umix0C7rtTPvTit4Y7fvLgeaIo5rh09Bb+g17y3qFWopHw=,iv:lOXelPqvPpjlviqy16CW8PoHjtch4yhN75GAwhi8avQ=,tag:scuJ+1V4aOKTBy6WRXUlcg==,type:str]
    pgp:
    -   created_at: '2021-01-15T23:22:05Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA7R8OyOD8bjEARAAgWxCGjUBox+5hoAbLGoNrx6cujirf46qkwrCzH3koUZk
            xyyR/48EAQTdoRPd8/5a55WRO38aqfhv4V/tvU6pXZ3DZskAYBnqy/bJJWIMfII2
            Pq4UosByed6Xuz4Gu+1abeW7Jj2rxLOQEVV/5sNCZ6hGtLl8YYhJRd87JbRo5GNm
            PrcXTsCXp2+uSW25roG55G+GcRpH4JG0+iFA3Wi/VditWCy5EFtgLOh1S8qIwYDf
            ptVxzA7NbDpnX9OMun8JlCAHI+ymJuXLCbSLSLR/zacWDuBV9pUNciuTBzJFeWWh
            pSUTRO3ZzSwtmrLbxoG2gMWEg8qDL5syA21T0uxFe6Pf12iPsHvEkhQ0ilkPeC7D
            xyrH2XQUqhODbJa7n8A9sPcZ6GV9p2UPnWCBfDq4Uzk/jTWcTINKUfxWIeO60BQ4
            EZE0cndJL/tgixY5GBP/5yIpomZ5w7lvnro/2ju+u+Pa125P3krIfiILqCKSdGVK
            //UCZV5mjV0IoBtEFj471rDrIycSrqvkP9p43So3JJz/3I8LWz19ku+6IbapneCS
            Za/G2L6RMMjnLkDXkp5eVPoGvEjnhlYAcsDkXv2US7se1tPktAGE/b3fyoym/yxx
            BJPqquXZ0n8oFLoDJWzz6Tyz/9/7N7yy538egtp7wSYmx/b0A4mp12F1aNa2eOfS
            4AHkaXg/NHDySP9hECTrpkRMkuHQDuC54Njh80fg8uJ2Shkh4KDlfdjw3+vaqEmg
            +w4rGVsfJOyda9I0Q4YGKjoc/2Sc8uvgIOS864ZXUga4trleUl/Wj2154v5wEyjh
            FbwA
            =dBZK
            -----END PGP MESSAGE-----
        fp: C8A1E2D47C35AB1C30288640940ED79CFA122C1A
    -   created_at: '2021-01-15T23:22:05Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wYwD5/DIMlnnmvcBBAA5RqhJQkLM+WJaFgrR4FLGrRNevdx49uNYrEt58Ppybu6U
            ko7naIUZWoXJoFLwMJw6QA0Y1jcRyOSB2Le1hf+k6CDzJoqFc1OULoshlaY4lpDO
            oeDjxGLdHCLmUiVXW5vo5zZMq7SA983ewy4havRW/hcVkvfN98e8WsjvqYHW69Lg
            AeRGybkji7BQUsl1QkwWOorU4VP34H7g9eH9keBm4iKP/tHgIOXJr43uMJKioBZS
            ifr88M0AAW91HfK3DlVL3XiT1G0/9eAc5KDu+KJ/7QR3gHxnn3ERDNHihBR56+FS
            pgA=
            =1fel
            -----END PGP MESSAGE-----
        fp: FEAE1C9C842D48A03C02C8BF23D2AAAD58DECDA0
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
