---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metric-server-charts
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
