---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  chart:
    spec:
      chart: tautulli
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    global:
      nameOverride: tautulli
    image:
      repository: ghcr.io/k8s-at-home/tautulli
      tag: v2.10.1
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 500Mi
