apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: heartbeat
  namespace: default
spec:
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: heartbeat-wget
            image: busybox
            args:
            - /bin/sh
            - -c
            - wget 'https://hc-ping.com/a91078ee-67bb-44ee-8577-a6b5ae581172' -T 10 -t 5
          restartPolicy: OnFailure

