---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-ips
  namespace: network
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16