# ArchiSteamFarm 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asf
  namespace: default
  labels:
    app: asf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asf
  template:
    metadata:
      labels:
        app: asf
    spec:
      containers:
      - name: asf
        image: justarchi/archisteamfarm:5.4.13.4
        env:
          - name: "ASF_ARGS"
            value: "--no-config-migrate"
        ports:
          - containerPort: 1242
        envFrom:
          - secretRef:
              name: asf-cryptkey
        volumeMounts:
          - name: asf-config-vol
            mountPath: /app/config
            readOnly: false
      - name: asf-autoclaim
        image: herocc/archisteamfarm:asfclaim
        command: ["/bin/sh", "-c", "echo 'waiting for warmup' && sleep 1m && node index.js"]
      volumes:
        - name: asf-config-vol
          projected:
            sources:
              - configMap:
                  name: asf-configmap
              - secret:
                  name: asf-account-creds
---
apiVersion: v1
kind: Service
metadata:
  name: asf
  namespace: default
spec:
  selector:
    app: asf
  ports:
    - protocol: TCP
      port: 1242
      targetPort: 1242

