# ArchiSteamFarm 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asf
  namespace: default
  labels:
    app: asf
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.asf: glob:~5.0.*.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asf
  template:
    metadata:
      labels:
        app: asf
    spec:
      containers:
      - name: asf
        image: justarchi/archisteamfarm:5.1.0.9
        ports:
          - containerPort: 1242
        envFrom:
          - secretRef:
              name: asf-cryptkey
        volumeMounts:
          - name: asf-config-vol
            mountPath: /app/config
            readOnly: false
      volumes:
        - name: asf-config-vol
          projected:
            sources:
              - configMap:
                  name: asf-configmap
              - secret:
                  name: asf-account-creds

