# https://packetstream.io/?psr=cCM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetstream
  namespace: default
  labels:
    app: packetstream
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetstream
  template:
    metadata:
      labels:
        app: packetstream
    spec:
      hostAliases:
      # Seemingly, GTAV was blocked after I started this container
      # Blacklist all the domains I know of, try to stop any potential spam
      # Hopefully this fixes things
      - ip: 127.0.0.1
        hostnames:
        - "socialclub.rockstargames.com"
        - "rockstargames.com"
        - "signin.rockstargames.com"
        - "view.rockstargames.com"
        - "support.rockstargames.com"
      containers:
      - name: psclient
        image: packetstream/psclient:latest
        env:
          - name: CID
            value: "cCM"

