---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    env:
      TZ: "America/New_York"
      EXTRA_ARGS: ["--exitimmediately"]
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      rclone-media:
        enabled: true
        mountPropagation: HostToContainer
        type: emptyDir
      rclone-config-vol:
        enabled: true
        type: secret
        name: rclone-media-conf-secret
      local-media:
        enabled: true
        existingClaim: media-library
        mountPath: /downloads
    additionalContainers:
      rclone-mount:
        name: rclone-mount
        image: rclone/rclone:1.59
        args: ["mount", "media:", "/rclonemount/", "--allow-non-empty", "--allow-other"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          preStop:
            exec:
              command: ["fusermount", "-uz", "/rclonemount/"]
        volumeMounts:
          - name: rclone-media
            mountPropagation: Bidirectional
            mountPath: /rclonemount/
            #readOnly: true
          - name: rclone-config-vol
            mountPath: /root/.config/rclone/
          - name: local-media
            mountPath: /downloads/
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 512Mi
