apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-secrets
    namespace: default
type: Opaque
data:
    TEST_SECRET: ENC[AES256_GCM,data:KnX+VXTzS50=,iv:c2zUBAjsoAIbjH42SMCPT6h+UQgRxAMx0+W1htIwzS0=,tag:oOGK490qp1YR2xddCssSqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-01T18:15:41Z"
    mac: ENC[AES256_GCM,data:N9A74BgGGwoipExGGiDpbe575jQfMSonrO7/TKsPVHcISWuwrOV6iDH1CcRgGsA14dkoPRyM6h8LsVqsP4jm5r/cLPIXFub4nw3060NkIn4KWBGJ/GbuwYw/T7jISsMbSuHWgN+FWS2wusC7WPR39dAiq66w34JtajWwLaG+FY8=,iv:aSOA8Yr6GYjOYBObKQ5xEWJgwny9fNt95mBlKo0+OP0=,tag:qYTLaQQvybvI3iE9wy0IOA==,type:str]
    pgp:
        - created_at: "2021-08-01T18:12:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7R8OyOD8bjEAQ/9Fm7W2Y8irGT1FhGTcANA+y2TSS1nTn4X/7KX3OqjNYTV
            6iuIozUkZGq0d4kvPiduCVvgQGj41D5RtLExhaAM6Wu9VoNRNrG0Z9nMaGgSbo1a
            +iuxkpzkyRd07UdYGgW70+i0cWUgXH13KhNEJ9Du7rOY8LT4mhw0u/IoWTgrvvUZ
            6UH7sZC7bL3sjzlxxZnJv+1V3gBgzpI/58z1FnYlVaSlFtsNY6Fr40Us2YLhaGDW
            LwYLQLT3CoIkra+OGqWZcutzjqDXJNBy7sU6Ve76jTHW9yz1XTupk9lutKg5AVnu
            o7jhtUJshZFPk8oHClwkbcXMXogs/ei5TndM6hl6Mw5r8HvBnRrkfB7KlV5X1AK7
            6M/bKo0amGpB2x6aqTDlRUIQlE4tSn4mFbbTvnlgAgyO5v3Bn5ZKbeyZ4AYzsRbg
            ukuJf6qWtlsZo6SVYXYfOGXIL48hnPzvoLSVoK/ys0hJN0VukhA7hpEb/w4onY/Y
            vixMQfylTZQWFzQdDlW5Q7CrC/JjR3hFWYzWrf+rzpIPkispoC/jhRmFWzqAJUd8
            zaMPzYPz5wUtvpiFl6L1p5Ks/na5cLbsULLw26o/N3jQ64So7/Use7FyjQXzjZe1
            NnIq0ZH2uxwDzfRbVkqk84gPTLOcQHM0xUuJ+SEKE3iitKFdqYIi2haGfXXIDt3S
            XgGWJopLMv8Qc8WcfYh3snLrGAybEzhxBYvxTsT8z+qPv8qNImuf7wez6aurM9dR
            yEWBYgadDG8oC4t54pNMeXS2ozyQgPcdGM34IJDxq+ViZ/q0eJaMlZfIIDiNuXw=
            =3FMX
            -----END PGP MESSAGE-----
          fp: C8A1E2D47C35AB1C30288640940ED79CFA122C1A
        - created_at: "2021-08-01T18:12:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hIwD5/DIMlnnmvcBA/9bv0PGbkpsC8dRkvAof/1Nr9S4jducNrOo9ych6StTH4HJ
            SBZlUtNu4SNgr8wlVkRoRJUv+NSnsFhaLuB1yl+6TG85hZvnn38P7UfE/g3HcjgN
            rZqBCpvHTln3mvk3O1aV2WQ+mmzwHxFm9VBgIA3m68Fu7n/FtitArK3d0kVe09Je
            AWWEkEW0GigGRo3I0z7dt/exDBYwRYusZjZbRq4doBBHjPUTfWuOWoqz+/2HbWk9
            kMMmCNAcYKcdnif+4rYdSlmhskofofYE4cVrxqvpb9EbGbJjfVO2vnSOCMtXmg==
            =cSKf
            -----END PGP MESSAGE-----
          fp: FEAE1C9C842D48A03C02C8BF23D2AAAD58DECDA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
