apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: network
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:mxBw3NilmL+YPJXQThjKaU0/fIAFsiF9+LSyDQl1OSWTx2h4Mq/XE8WkT4IEtTmYg0GSx5vu0VU/GVaYDXXAdqIDHn0RPXQ1Z/BmlJxeiFZxIos3mwh6VN6cDOxtFaxN4TlYVcwWwHi+KHxJa0FsPEIGCRA5KP58yEpf0uFISxRaHuO9FNjNVJiiE/hCzvbNraXbN6DcI32lzyft1ZJzm/r0fwnBnSGB2bQXLfcNGIOxW8OllAP/ocyDmmiJZRHhjG3Is+cT0GbAQ5guPrnA8AwWhhtFfkhk,iv:317sGHxfUwN8g9wHRlYki5KZxZVRZ1h7QWmy8FWmB1s=,tag:uNSkJ1SvpK8Zv7/CWiPOkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-29T06:36:37Z"
    mac: ENC[AES256_GCM,data:mDetlVHwNLmSn+q01K1StCBazwJjgdiK2Bk0Dm03V9OUylZK+jju2FnYZB/esc1QVjJ9yenezbSLL5/ie1UK7QJyti4bRsheVsivdElxedX5B3NEMbQagb7Y+SkH/BAVNE2XJuCnNuZhDW6Bu4R36u6GRcgRFXlFt9SAf4UDNTk=,iv:cw1XcP+vRBW8ScmQ73FJgU5pCFzz3L1CRAsBaLrgUEU=,tag:XgoBvW6IULHVhnX09BWqDQ==,type:str]
    pgp:
        - created_at: "2020-09-01T21:52:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7R8OyOD8bjEARAAgjA1HcQ1jtVPvMm/6+XJEPygYK5oy6NHxUFTjbXHaS/5
            KUIJv62Aj89zlCbelxPqfKH8VKghAJEKfj6UbVngKvVnucYU1ayZeaOxJy5HigdK
            DHpkS1zNAq8J6CLNU4a7gciifkYq7GvmTifNBvdwPy3VcaQu9NGFFcGTlrQ7yskB
            sKQBy+mobf8695WOZFYmIP6OjFAPpSzZUCHg0B74tmDcDBRf/A46dzw5hr/TRnt3
            XDq/cQfaqk6maML3Sw0oMwqA0wcWFYhrsozo8+FKQ1+mT7y4WelzOIh45nb+tJ2R
            r619EHJXmeQbsZ3lAKBOIaocijjtWz7cH6JdNwg27DBDE31B2GIqZgpuAuhb2doh
            syBbO57rROv1UUUTOQxIs9UWAAWZs0Xe+m1jaH6xWnTahUo9a9UussfOEWGBwEbI
            pZB7JhV2U+1stHWGIGbfnfYc2eAl2nsNOdBeED6G/C2vjdPC2q3DPSPB3NCMty13
            pvUvEybbKJ+KLsSLn13MDyzlk0vhSHCf3rqtz8Q5oSeXFZ6/VeeSr4nQyRCb3xy8
            3XnykVQD9jDYGLZGWvb3DGs4GbAD7TuNPjG2Q+L4wSHaA+x36TximX8/jEncPFoX
            kawr5L4Ity4A+C4Bdr1iVeBkCf/J4qQarQ0TlzOrfjaP/O2beo76WLzyPXi5oQzS
            XgHlIh9MqWL3UtW1TOH3ESz/vgf53e5qWAqnQ28/pFyVUfvpR9gFjCCu0ltA3nQ7
            ithc03EWe7WSueMbbmStPB+c5PG9jZwWfQlWzK8D0gurszTfjm2wbN+IdpTHRGk=
            =d0e1
            -----END PGP MESSAGE-----
          fp: C8A1E2D47C35AB1C30288640940ED79CFA122C1A
        - created_at: "2020-09-01T21:52:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hIwD5/DIMlnnmvcBA/9Xm7fvr4R7lvPxHi0cBg7791b7R12Umf8fnwY4LpkzxcQX
            TEiCNbHjrP8wK+hM9e65/2+/MIr0z2uBtkjsxq1D/1QruL42nfzgQPPzIW3WpPNS
            L6b+N0tTw09GvFvnp7imrrsKHq4jZOUIT/JURtkN2FJNWyvzGUUNSmlTTsctJNJe
            AXu7p406emQM+lFbmxw0ei5jWXNqn4YRre8qTLqPXNVy++/pOaZkkK8FM9WW24wi
            +eYrOKAP3RvYiKTXkRpdfZ/Z9WQ0AAg+jjR++Bo6RgBu6Crjekjr7ZTl2H1RnA==
            =96wl
            -----END PGP MESSAGE-----
          fp: FEAE1C9C842D48A03C02C8BF23D2AAAD58DECDA0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
