---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflared-tunnel
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  dependsOn:
    - name: traefik
      namespace: network
  values:
    nameOverride: *app
    resources:
      limits: &resources
        memory: 256Mi
      requests:
        <<: *resources
        cpu: 10m
    cloudflare:
      tunnelName: "home-k8s"
      secretName: cloudflare-tunnel-secrets
      enableWarp: true
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://traefik.network.svc.cluster.local.:443
          originRequest:
            originServerName: external.${SECRET_DOMAIN}

