---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
    env:
      TZ: "America/New_York"
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config
      downloads:
        enabled: true
        existingClaim: media-library
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: "network-internal-only@kubernetescrd"
      hosts:
        - host: nzbget.${SECRET_DOMAIN}
    probes:
      liveness:
        enabled: true
        # custom: true
        # spec:
        #   exec:
        #     - /usr/bin/env
        #     - bash
        #     - -c
        #     - ./nzbget -L S
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 512Mi
