---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzb-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
