#cloud-config

hostname: ${ hostname }

install:
  reboot: true
  auto: true # Automated install
  device: "auto" # largest

# bundles:
#   - targets:
#     - run://quay.io/kairos/community-bundles:kairos_latest
#     # - run://quay.io/kairos/packages:k9s-utils-0.26.7

users:
- name: cc
  shell: /bin/bash
  groups: 
    - admin
  passwd: kairos
  ssh_authorized_keys:
    - github:HeroCC

k3s:
  enabled: true
  args:
    - --disable=traefik,servicelb

p2p:
  # If DHT is disabled, EdgeVPN will only communicate over LAN
  disable_dht: false
  role: "${ p2p_role }"

  # network_token is the shared secret used by the nodes to co-ordinate with p2p.
  # Setting a network token implies auto.enable = true.
  # To disable, just set auto.enable = false
  network_token: ${ edgevpn_token }