---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/node-feature-discovery
      tag: "v0.8.1"

