---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: rook-ceph-block
