---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media
spec:
  interval: 5m0s
  chart:
    spec:
      chart: nzbhydra2
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v4.7.1
    env:
      TZ: 'America/New York'
    persistence:
      config:
        enabled: true
        existingClaim: nzbhydra-config
    probes:
      liveness:
        spec:
          httpGet:
            path: /nzbhydra2/actuator/health/livenessState
      readiness:
        spec:
          httpGet:
            path: /nzbhydra2/actuator/health/livenessState
      startup:
        spec:
          httpGet:
            path: /nzbhydra2/actuator/health/livenessState
    initContainers:
      - name: clearLogs
        image: busybox
        command:
          - rm
          - -rv
          - /config/logs/
        volumeMounts:
          - mountPath: /config
            name: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 512Mi
