---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media
spec:
  interval: 5m0s
  chart:
    spec:
      chart: nzbhydra2
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v3.17.3
    env:
      TZ: 'America/New York'
    persistence:
      config:
        enabled: true
        existingClaim: nzbhydra-config
