---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmirror
  namespace: default
  labels:
    app: mmirror
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.magicmirror: glob:~v2.14.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmirror
  template:
    metadata:
      labels:
        app: mmirror
    spec:
      initContainers:
        - name: get-extmodules
          image: alpine/git:latest
          command: ["/bin/sh", "-c"]
          volumeMounts:
            - name: ext-modules
              mountPath: "/modules"
          args:
            - |
              cd /modules
              git clone https://github.com/MMM-CalendarExt2/MMM-CalendarExt2.git
        - name: build-extmodules
          image: node:lts-slim
          command: ["/bin/sh", "-c"]
          volumeMounts:
            - name: ext-modules
              mountPath: "/modules"
          args:
            - |
              cd /modules
              for d in ./*/; do (cd "$d" && npm install) ; done
      containers:
      - name: magicmirror
        image: bastilimbach/docker-magicmirror:v2.14.0
        ports:
        - name: web
          containerPort: 8080
        env:
        - name: TZ
          value: "America/New_York"
        envFrom:
        - secretRef:
            name: mmirror-envsecret
        volumeMounts:
        - name: ext-modules
          mountPath: "/opt/magic_mirror/modules/ext"
        - name: mmirror-config-vol
          mountPath: "/opt/magic_mirror/config/config.js.template"
          subPath: "config.js.template"
      volumes:
      - name: ext-modules
        emptyDir: {}
      - name: mmirror-config-vol
        configMap:
          name: mmirror-configmap
