---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmirror
  namespace: default
  labels:
    app: mmirror
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.magicmirror: glob:~v2.14.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmirror
  template:
    metadata:
      labels:
        app: mmirror
    spec:
      containers:
      - name: magicmirror
        image: bastilimbach/docker-magicmirror:v2.14.0
        ports:
        - name: web
          containerPort: 8080
        env:
        - name: TZ
          value: "America/New_York"
        envFrom:
        - secretRef:
            name: mmirror-envsecret
        volumeMounts:
        - name: mmcal2-module
          mountPath: "/opt/magic_mirror/modules/MMM-CalendarExt2"
          subPath: "CalendarExt2"
        - name: mmirror-config-vol
          mountPath: "/opt/magic_mirror/config/config.js.template"
          subPath: "config.js.template"
      volumes:
      - name: mmcal2-module
        gitRepo:
          repository: "https://github.com/MMM-CalendarExt2/MMM-CalendarExt2.git"
          revision: "d922147466f04f52a38d83cf03bd54c7454b60d7"
      - name: mmirror-config-vol
        configMap:
          name: mmirror-configmap
