---
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: default
spec:
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    processAgent:
      enabled: true
      processCollection: true
    admissionController:
      # Enable the admissionController to automatically inject APM and DogStatsD config and standard tags (env, service, version) into your pods
      enabled: true             # default: true
      # Enable injecting config without having the pod label: admission.datadoghq.com/enabled="true"
      mutateUnlabelled: true    # default false
  global:
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:7.48.0
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:7
