---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog-operator
      version: v1.2.1
      sourceRef:
        kind: HelmRepository
        name: datadog-charts
        namespace: flux-system
  values:
    installCRDs: true
    datadogAgent:
      enabled: true
    watchNamespaces:
      - "" # watch all namespaces