name: Validate Charts

on: 
  push:
    branches:
     - master

jobs: 
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm releases in deployments dir
        uses: stefanprodan/hrval-action@v4.0.0
        with:
          helmRelease: deployments/
          helmVersion: v3

