name: Validate Charts

on: 
  push:
    branches:
     - master

jobs: 
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm releases in deployments dir
        uses: atoscerebro/flux-validate-action@v1
        with:
          flux-version: 0.24.0

